# Generated by Django 4.1.3 on 2022-11-11 12:31

from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    def load_project_types_from_fixture(apps, schema_editor):
        call_command("loaddata", "projecttype.yml")

    def delete_projecttypes(apps, schema_editor):
        ProjectType = apps.get_model("infraohjelmointi_api", "ProjectType")
        ProjectType.objects.all().delete()

    def load_projects_from_fixture(apps, schema_editor):
        call_command("loaddata", "project.yml")

    def delete_projects(apps, schema_editor):
        Project = apps.get_model("infraohjelmointi_api", "Project")
        Project.objects.all().delete()

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(load_project_types_from_fixture, delete_projecttypes),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('HKRprojectID', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('updated_date', models.DateTimeField(verbose_name='date updated')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projecttype')),
            ],
        ),
        migrations.RunPython(load_projects_from_fixture, delete_projects),
    ]
