# Generated by Django 4.1.3 on 2022-11-17 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budgetMain', models.IntegerField(blank=True, null=True)),
                ('budgetPlan', models.IntegerField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('siteName', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('need', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('pwProjectId', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('projectPhase', models.CharField(choices=[('PROP', 'Hanke-ehdotus'), ('DESG', 'Yleissuunnittelu'), ('PROG', 'Ohjelmointi'), ('DRAI', 'Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos'), ('DRAA', 'Katu-/puistosuunnitelmaehdotus ja hyväksyminen'), ('CONP', 'Rakennussuunnitelma'), ('CONW', 'Odottaa rakentamista'), ('CONS', 'Rakentaminen'), ('WARP', 'Takuuaika'), ('COMP', 'Valmis / ylläpidossa')], default='PROP', max_length=4)),
                ('programmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pwProjectId', models.UUIDField(blank=True, null=True)),
                ('taskType', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Past'), ('U', 'Upcoming')], default='U', max_length=2)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField(auto_now=True)),
                ('realizedCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plannedCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('riskAssess', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='HKRprojectID',
        ),
        migrations.AddField(
            model_name='project',
            name='comittedCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='constructionPhaseDetail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractPrepEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractPrepStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='costForecast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delays',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estDesignEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estDesignEndYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estDesignStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estPlanningStartYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='perfAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='programmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='projectPhase',
            field=models.CharField(choices=[('PROP', 'Hanke-ehdotus'), ('DESG', 'Yleissuunnittelu'), ('PROG', 'Ohjelmointi'), ('DRAI', 'Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos'), ('DRAA', 'Katu-/puistosuunnitelmaehdotus ja hyväksyminen'), ('CONP', 'Rakennussuunnitelma'), ('CONW', 'Odottaa rakentamista'), ('CONS', 'Rakentaminen'), ('WARP', 'Takuuaika'), ('COMP', 'Valmis / ylläpidossa')], default='PROP', max_length=4),
        ),
        migrations.AddField(
            model_name='project',
            name='pwProjectId',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='realizedCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='riskAssess',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sapNetworkNumber',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sapProjectNumber',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spentCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tiedCurrYear',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='unitCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='warrantyExpireDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='warrantyStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('PROJECTCOMPLEX', 'Hankekokonaisuus'), ('STREET', 'Katu'), ('TRAFFIC', 'Liikenne'), ('SPORTS', 'Liikunta'), ('OMASTADI', 'Omastadi'), ('PROJECTAREA', 'Projektialue'), ('PARK', 'Puisto tai taitorakenne')], max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('id', 'pwProjectId', 'sapProjectNumber', 'sapNetworkNumber'), name='Unique together Project Ids'),
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.project'),
        ),
        migrations.AddField(
            model_name='projectset',
            name='responsiblePerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='favPersons',
            field=models.ManyToManyField(related_name='favourite', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='personConstruction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='construction', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='personPlanning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planning', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='personProgramming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programming', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectarea'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectset'),
        ),
        migrations.AddField(
            model_name='project',
            name='siteId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.budgetitem'),
        ),
    ]
