# Generated by Django 4.1.3 on 2022-11-22 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("budgetMain", models.IntegerField(blank=True, null=True)),
                ("budgetPlan", models.IntegerField(blank=True, null=True)),
                ("site", models.CharField(blank=True, max_length=200, null=True)),
                ("siteName", models.CharField(blank=True, max_length=200, null=True)),
                ("district", models.CharField(blank=True, max_length=200, null=True)),
                ("need", models.DecimalField(decimal_places=2, max_digits=20)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=14)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("areaName", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("hkrId", models.UUIDField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("design", "Design"),
                            ("ohjelmointi", "Programming"),
                            ("draftInitiation", "DraftInitiation"),
                            ("draftApproval", "DraftApproval"),
                            ("constructionPlan", "ConstructionPlan"),
                            ("constructionWait", "ConstructionWait"),
                            ("construction", "Construction"),
                            ("warrantyPeriod", "WarrantyPeriod"),
                            ("completed", "Completed"),
                        ],
                        default="proposal",
                        max_length=16,
                    ),
                ),
                ("programmed", models.BooleanField(default=False)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hkrId", models.UUIDField(blank=True, null=True)),
                ("taskType", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past", "Past"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="upcoming",
                        max_length=8,
                    ),
                ),
                ("startDate", models.DateField(auto_now=True)),
                ("endDate", models.DateField(auto_now=True)),
                ("realizedCost", models.DecimalField(decimal_places=2, max_digits=20)),
                ("plannedCost", models.DecimalField(decimal_places=2, max_digits=20)),
                ("riskAssess", models.CharField(max_length=200)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="HKRprojectID",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="project",
            name="comittedCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="constructionPhaseDetail",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contractPrepEndDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contractPrepStartDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="costForecast",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="createdDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="delays",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="estDesignEndDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="estDesignEndYear",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="estDesignStartDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="estPlanningStartYear",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="hkrId",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="perfAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal"),
                    ("design", "Design"),
                    ("programming", "Programming"),
                    ("draftInitiation", "DraftInitiation"),
                    ("draftApproval", "DraftApproval"),
                    ("constructionPlan", "ConstructionPlan"),
                    ("constructionWait", "ConstructionWait"),
                    ("construction", "Construction"),
                    ("warrantyPeriod", "WarrantyPeriod"),
                    ("completed", "Completed"),
                ],
                default="proposal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="low",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="programmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="realizedCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="riskAssess",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sapNetwork",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sapProject",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="spentCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tiedCurrYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="unitCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="warrantyExpireDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="warrantyStartDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="createdDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projecttype",
            name="updatedDate",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projecttype",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="projectSet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectset",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("id", "hkrId", "sapProject", "sapNetwork", "projectSet"),
                name="Unique together Constraint Project",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="projectId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.project",
            ),
        ),
        migrations.AddField(
            model_name="projectset",
            name="responsiblePerson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectarea",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="favPersons",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favourite",
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="personConstruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="construction",
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="personPlanning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="planning",
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="personProgramming",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="programming",
                to="infraohjelmointi_api.person",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="siteId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.budgetitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectset",
            constraint=models.UniqueConstraint(
                fields=("id", "hkrId"), name="Unique together Constraint ProjectSet"
            ),
        ),
    ]
