# Generated by Django 4.1.3 on 2022-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0002_budgetitem_person_projectarea_projectset_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectPhase',
            field=models.CharField(choices=[('PROPOSAL', 'Hanke-ehdotus'), ('DESIGN', 'Yleissuunnittelu'), ('PROGRAMMING', 'Ohjelmointi'), ('DRAFT_INITIATION', 'Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos'), ('DRAFT_APPROVAL', 'Katu-/puistosuunnitelmaehdotus ja hyväksyminen'), ('CONSTRUCTION_PLAN', 'Rakennussuunnitelma'), ('CONSTRUCTION_WAIT', 'Odottaa rakentamista'), ('CONSTRUCTION', 'Rakentaminen'), ('WARRANTY_PERIOD', 'Takuuaika'), ('COMPLETED', 'Valmis / ylläpidossa')], default='PROPOSAL', max_length=17),
        ),
        migrations.AlterField(
            model_name='projectset',
            name='projectPhase',
            field=models.CharField(choices=[('PROPOSAL', 'Hanke-ehdotus'), ('DESIGN', 'Yleissuunnittelu'), ('PROGRAMMING', 'Ohjelmointi'), ('DRAFT_INITIATION', 'Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos'), ('DRAFT_APPROVAL', 'Katu-/puistosuunnitelmaehdotus ja hyväksyminen'), ('CONSTRUCTION_PLAN', 'Rakennussuunnitelma'), ('CONSTRUCTION_WAIT', 'Odottaa rakentamista'), ('CONSTRUCTION', 'Rakentaminen'), ('WARRANTY_PERIOD', 'Takuuaika'), ('COMPLETED', 'Valmis / ylläpidossa')], default='PROPOSAL', max_length=17),
        ),
    ]
