# Generated by Django 4.1.3 on 2022-11-29 09:04

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0003_data_phase_priority_type_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.person')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNote',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('content', models.TextField(blank=True, default='')),
                ('createdDate', models.DateTimeField(blank=True, editable=False)),
                ('updatedDate', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='infraohjelmointi_api.person')),
                ('updatedBy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.person')),
            ],
            options={
                'verbose_name': 'historical note',
                'verbose_name_plural': 'historical notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
