# Generated by Django 4.1.3 on 2022-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0003_alter_projectset_responsibleperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entityName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Sample description', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
