# Generated by Django 4.1.3 on 2022-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0004_project_entityname_alter_project_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="hkrId",
        ),
        migrations.AddField(
            model_name="project",
            name="hkrId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="projectset",
            name="hkrId",
        ),
        migrations.AddField(
            model_name="projectset",
            name="hkrId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="task",
            name="hkrId",
        ),
        migrations.AddField(
            model_name="task",
            name="hkrId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
