# Generated by Django 4.1.3 on 2022-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0004_alter_budgetitem_need_alter_project_comittedcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favPersons',
            field=models.ManyToManyField(null=True, related_name='favourite', to='infraohjelmointi_api.person'),
        ),
    ]
