# Generated by Django 4.1.3 on 2022-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0005_alter_project_hkrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hashTags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
