# Generated by Django 4.1.3 on 2022-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0005_alter_project_favpersons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favPersons',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to='infraohjelmointi_api.person'),
        ),
    ]
