# Generated by Django 4.1.3 on 2022-12-02 09:31

from django.db import migrations


def read_excel_populate_table(apps, schema_editor):

    Project = apps.get_model("infraohjelmointi_api", "Project")


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0005_alter_note_project_alter_note_updatedby"),
    ]

    operations = []
