# Generated by Django 4.1.3 on 2022-12-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0005_alter_note_project_alter_note_updatedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="effectHousing",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="project",
            name="sapProject",
        ),
        migrations.AddField(
            model_name="project",
            name="sapProject",
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
