# Generated by Django 4.1.3 on 2022-12-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0006_alter_project_sapproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sapProject',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
