# Generated by Django 4.1.3 on 2022-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0007_auto_excel_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hkrId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
