# Generated by Django 4.1.3 on 2022-11-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0008_projectphase_projectpriority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="phase",
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectphase",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="priority",
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectpriority",
            ),
        ),
    ]
