# Generated by Django 4.1.3 on 2022-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0008_alter_projectset_hkrid_alter_task_hkrid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="effectHousing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetForecast1CurrentYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetForecast2CurrentYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetForecast3CurrentYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetForecast4CurrentYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetProposalCurrentYearPlus1",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budgetProposalCurrentYearPlus2",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="comittedCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="costForecast",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="perfAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus10",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus3",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus4",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus5",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus6",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus7",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus8",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preliminaryCurrentYearPlus9",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="realizedCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="spentCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tiedCurrYear",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="unitCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
    ]
