# Generated by Django 4.1.3 on 2022-11-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0008_person_created_date_person_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectPhase',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='projectset',
            old_name='projectPhase',
            new_name='phase',
        ),
    ]
