# Generated by Django 4.1.3 on 2022-12-12 12:11

from django.db import migrations

# removed the excel migration function from here since they are not migrated automatically
# can't remove the migration file since the migration numbering system would break
class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0009_alter_project_options_project_category_and_more",
        ),
    ]
    # NO NEED TO RUN THIS ONE BECAUSE THERE IS A COMMAND TO RUN DATA FROM EXCEL
    operations = [
        # migrations.RunPython(
        #     partial(
        #         migrateExcel,
        #         budgetExcelPath="/app/infraohjelmointi_api/mock_data/budget23.xlsx",
        #         planExcelPath="/app/infraohjelmointi_api/mock_data/plan23.xlsx",
        #     )
        # ),
    ]
