# Generated by Django 4.1.3 on 2022-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0009_rename_projectphase_project_phase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='Doe', max_length=200),
            preserve_default=False,
        ),
    ]
