# Generated by Django 4.1.3 on 2022-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0010_rename_name_person_firstname_person_lastname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="Unique together Project Ids",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="sapNetworkNumber",
            new_name="sapNetwork",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="sapProjectNumber",
            new_name="sapProject",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("id", "pwProjectId", "sapProject", "sapNetwork", "projectSet"),
                name="Unique together Project Ids",
            ),
        ),
    ]
