# Generated by Django 4.1.3 on 2022-11-23 12:48

from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion
import uuid


def delete_foreign_dependent_data(apps, schema_editor):
    ProjectPhase = apps.get_model("infraohjelmointi_api", "ProjectPhase")
    ProjectType = apps.get_model("infraohjelmointi_api", "ProjectType")
    ProjectPriority = apps.get_model("infraohjelmointi_api", "ProjectPriority")
    Project = apps.get_model("infraohjelmointi_api", "Project")
    ProjectSet = apps.get_model("infraohjelmointi_api", "ProjectSet")
    Task = apps.get_model("infraohjelmointi_api", "Task")

    Task.objects.all().delete()
    ProjectSet.objects.all().delete()
    Project.objects.all().delete()
    ProjectPhase.objects.all().delete()
    ProjectType.objects.all().delete()
    ProjectPriority.objects.all().delete()


def populate_Phase_Type_priority_status(apps, schema_editor):

    phases = [
        "proposal",
        "design",
        "programming",
        "draftInitiation",
        "draftApproval",
        "constructionPlan",
        "constructionWait",
        "construction",
        "warrantyPeriod" "completed",
    ]
    types = [
        "projectComplex",
        "street",
        "traffic",
        "sports",
        "omaStadi",
        "projectArea",
        "park",
    ]
    statuses = ["active", "past", "upcomming"]
    priorities = ["low", "medium", "high"]
    ProjectPhase = apps.get_model("infraohjelmointi_api", "ProjectPhase")
    ProjectType = apps.get_model("infraohjelmointi_api", "ProjectType")
    ProjectPriority = apps.get_model("infraohjelmointi_api", "ProjectPriority")
    TaskStatus = apps.get_model("infraohjelmointi_api", "TaskStatus")

    for phase in phases:
        ProjectPhase.objects.create(value=phase)

    for priority in priorities:
        ProjectPriority.objects.create(value=priority)
    for _type in types:
        ProjectType.objects.create(value=_type)
    for status in statuses:
        TaskStatus.objects.create(value=status)


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0010_alter_projectset_phase"),
    ]

    operations = [
        migrations.RunPython(delete_foreign_dependent_data),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=30)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.taskstatus",
            ),
        ),
        migrations.RunPython(populate_Phase_Type_priority_status),
    ]
