# Generated by Django 4.1.3 on 2022-12-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0010_auto_excel_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estPlanningStartYear',
        ),
        migrations.AddField(
            model_name='project',
            name='estPlanningEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estPlanningStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
