# Generated by Django 4.1.3 on 2022-11-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0011_auto_20221123_1248"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sapNetwork",
        ),
        migrations.AddField(
            model_name="project",
            name="sapNetwork",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="sapProject",
        ),
        migrations.AddField(
            model_name="project",
            name="sapProject",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
