# Generated by Django 4.1.3 on 2022-11-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0011_remove_project_unique together project ids_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='Unique together Project Ids',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectArea',
            new_name='area',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('id', 'pwProjectId', 'sapProject', 'sapNetwork', 'projectSet'), name='Unique together Constraint Project'),
        ),
        migrations.AddConstraint(
            model_name='projectset',
            constraint=models.UniqueConstraint(fields=('id', 'pwProjectId'), name='Unique together Constraint ProjectSet'),
        ),
    ]
