# Generated by Django 4.1.3 on 2022-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0012_remove_project_unique together project ids_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='Unique together Constraint Project',
        ),
        migrations.RemoveConstraint(
            model_name='projectset',
            name='Unique together Constraint ProjectSet',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pwProjectId',
            new_name='hkrId',
        ),
        migrations.RenameField(
            model_name='projectset',
            old_name='pwProjectId',
            new_name='hkrId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pwProjectId',
            new_name='hkrId',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('id', 'hkrId', 'sapProject', 'sapNetwork', 'projectSet'), name='Unique together Constraint Project'),
        ),
        migrations.AddConstraint(
            model_name='projectset',
            constraint=models.UniqueConstraint(fields=('id', 'hkrId'), name='Unique together Constraint ProjectSet'),
        ),
    ]
