# Generated by Django 4.1.3 on 2022-11-24 12:05

from django.db import migrations


def populate_area_data(apps, schema_editor):
    ProjectArea = apps.get_model("infraohjelmointi_api", "ProjectArea")
    areaNames = [
        "Honkasuo",
        "Kalasatama",
        "Kruunuvuorenranta",
        "Kuninkaantammi",
        "Länsisatama",
        "Malmin lentokenttäalue",
        "Pasila",
        "Östersundom",
    ]
    for area in areaNames:
        ProjectArea.objects.create(areaName=area, location="Helsinki")


class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0012_alter_project_sapnetwork_alter_project_sapproject",
        ),
    ]

    operations = [migrations.RunPython(populate_area_data)]
