# Generated by Django 4.1.3 on 2022-11-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0013_auto_20221124_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectarea',
            old_name='areaName',
            new_name='value',
        ),
    ]
