# Generated by Django 4.1.3 on 2022-12-19 10:20

from django.db import migrations


def populate_category_data(apps, schema_editor):
    ProjectCategory = apps.get_model("infraohjelmointi_api", "ProjectCategory")
    projectCategories = [
        "K1",
        "K2",
        "K3",
        "K4",
        "K5",
        "K5.1",
        "K5.2",
        "K5.3",
        "K5.4",
        "K5.5",
    ]
    for category in projectCategories:
        ProjectCategory.objects.create(value=category)


def migrate_existing_category_data(apps, schema_editor):
    Project = apps.get_model("infraohjelmointi_api", "Project")
    ProjectCategory = apps.get_model("infraohjelmointi_api", "ProjectCategory")
    for project in Project.objects.all():
        if project.category is not None:
            cleanedCategory = project.category.rstrip("[_+!@#$.?^\s]+$").capitalize()
            if cleanedCategory in [
                "K1",
                "K2",
                "K3",
                "K4",
                "K5",
                "K5.1",
                "K5.2",
                "K5.3",
                "K5.4",
                "K5.5",
            ]:
                category = ProjectCategory.objects.get(value=cleanedCategory)
                project.category_temp = category
                project.save()


def populate_construction_phase_detail_data(apps, schema_editor):
    ConPhaseDetail = apps.get_model("infraohjelmointi_api", "ConPhaseDetail")
    conPhases = ["preConstruction", "firstPhase", "firstPhaseComplete", "secondPhase"]
    for phase in conPhases:
        ConPhaseDetail.objects.create(value=phase)


class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0013_conphasedetail_projectcategory_projectrisk_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_category_data),
        migrations.RunPython(migrate_existing_category_data),
        migrations.RunPython(populate_construction_phase_detail_data),
    ]
