# Generated by Django 4.1.3 on 2022-12-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0013_conphasedetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="constructionPhaseDetail",
        ),
        migrations.AddField(
            model_name="project",
            name="constructionPhaseDetail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.conphasedetail",
            ),
        ),
    ]
