# Generated by Django 4.1.3 on 2022-12-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0014_auto_conphase_category_risk_populate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="category_temp",
            new_name="category",
        ),
    ]
