# Generated by Django 4.1.3 on 2022-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0014_rename_created_date_person_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Hanke-ehdotus', 'Proposal'), ('Yleissuunnittelu', 'Design'), ('Ohjelmointi', 'Programming'), ('Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos', 'Draft Initiation'), ('Katu-/puistosuunnitelmaehdotus ja hyväksyminen', 'Draft Approval'), ('Rakennussuunnitelma', 'Construction Plan'), ('Odottaa rakentamista', 'Construction Wait'), ('Rakentaminen', 'Construction'), ('Takuuaika', 'Warranty Period'), ('Valmis / ylläpidossa', 'Completed')], default='Hanke-ehdotus', max_length=54),
        ),
        migrations.AlterField(
            model_name='projectset',
            name='phase',
            field=models.CharField(choices=[('Hanke-ehdotus', 'Proposal'), ('Yleissuunnittelu', 'Design'), ('Ohjelmointi', 'Programming'), ('Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos', 'Draft Initiation'), ('Katu-/puistosuunnitelmaehdotus ja hyväksyminen', 'Draft Approval'), ('Rakennussuunnitelma', 'Construction Plan'), ('Odottaa rakentamista', 'Construction Wait'), ('Rakentaminen', 'Construction'), ('Takuuaika', 'Warranty Period'), ('Valmis / ylläpidossa', 'Completed')], default='Hanke-ehdotus', max_length=54),
        ),
    ]
