# Generated by Django 4.1.3 on 2022-11-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0015_alter_project_phase_alter_projectset_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Hanke-ehdotus', 'Proposal'), ('Yleissuunnittelu', 'Design'), ('Ohjelmointi', 'Programming'), ('Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos', 'DraftInitiation'), ('Katu-/puistosuunnitelmaehdotus ja hyväksyminen', 'DraftApproval'), ('Rakennussuunnitelma', 'ConstructionPlan'), ('Odottaa rakentamista', 'ConstructionWait'), ('Rakentaminen', 'Construction'), ('Takuuaika', 'WarrantyPeriod'), ('Valmis / ylläpidossa', 'Completed')], default='Hanke-ehdotus', max_length=54),
        ),
        migrations.AlterField(
            model_name='projectset',
            name='phase',
            field=models.CharField(choices=[('Hanke-ehdotus', 'Proposal'), ('Yleissuunnittelu', 'Design'), ('Ohjelmointi', 'Programming'), ('Katu- ja puistosuunnittelun aloitus/suunnitelmaluonnos', 'DraftInitiation'), ('Katu-/puistosuunnitelmaehdotus ja hyväksyminen', 'DraftApproval'), ('Rakennussuunnitelma', 'ConstructionPlan'), ('Odottaa rakentamista', 'ConstructionWait'), ('Rakentaminen', 'Construction'), ('Takuuaika', 'WarrantyPeriod'), ('Valmis / ylläpidossa', 'Completed')], default='Hanke-ehdotus', max_length=54),
        ),
    ]
