# Generated by Django 4.1.3 on 2022-12-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0015_auto_alter_category_categorytemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='riskAssess',
            new_name='riskAssessment',
        ),
    ]
