# Generated by Django 4.1.3 on 2022-11-24 14:17

from django.db import migrations


def rename_phase_value(apps, schema_editor):
    ProjectPhase = apps.get_model("infraohjelmointi_api", "ProjectPhase")
    phaseObj = ProjectPhase.objects.get(value="warrantyPeriodcompleted")
    phaseObj.value = "warrantyPeriod"

    ProjectPhase.objects.create(value="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0015_auto_20221124_1404"),
    ]

    operations = [
        migrations.RunPython(rename_phase_value),
    ]
