# Generated by Django 4.1.3 on 2022-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0016_project_category_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gravel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='louhi',
            field=models.BooleanField(default=False),
        ),
    ]
