# Generated by Django 4.1.3 on 2022-11-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0016_alter_project_phase_alter_projectset_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('design', 'Design'), ('ohjelmointi', 'Programming'), ('draftInitiation', 'DraftInitiation'), ('draftApproval', 'DraftApproval'), ('constructionPlan', 'ConstructionPlan'), ('constructionWait', 'ConstructionWait'), ('construction', 'Construction'), ('warrantyPeriod', 'WarrantyPeriod'), ('completed', 'Completed')], default='proposal', max_length=16),
        ),
        migrations.AlterField(
            model_name='projectset',
            name='phase',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('design', 'Design'), ('ohjelmointi', 'Programming'), ('draftInitiation', 'DraftInitiation'), ('draftApproval', 'DraftApproval'), ('constructionPlan', 'ConstructionPlan'), ('constructionWait', 'ConstructionWait'), ('construction', 'Construction'), ('warrantyPeriod', 'WarrantyPeriod'), ('completed', 'Completed')], default='proposal', max_length=16),
        ),
    ]
