# Generated by Django 4.1.3 on 2022-11-24 14:20

from django.db import migrations


def rename_phase_value(apps, schema_editor):
    ProjectPhase = apps.get_model("infraohjelmointi_api", "ProjectPhase")
    phaseObj = ProjectPhase.objects.get(value="warrantyPeriodcompleted")
    phaseObj.value = "warrantyPeriod"
    phaseObj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0016_auto_20221124_1417"),
    ]

    operations = [
        migrations.RunPython(rename_phase_value),
    ]
