# Generated by Django 4.1.3 on 2022-11-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0017_alter_project_phase_alter_projectset_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('design', 'Design'), ('programming', 'Programming'), ('draftInitiation', 'DraftInitiation'), ('draftApproval', 'DraftApproval'), ('constructionPlan', 'ConstructionPlan'), ('constructionWait', 'ConstructionWait'), ('construction', 'Construction'), ('warrantyPeriod', 'WarrantyPeriod'), ('completed', 'Completed')], default='proposal', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('projectComplex', 'ProjectComplex'), ('stret', 'Street'), ('traffic', 'Traffic'), ('sports', 'Sports'), ('omastadi', 'Omastadi'), ('projectArea', 'ProjectArea'), ('park', 'Park')], max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('acive', 'Active'), ('past', 'Past'), ('upcoming', 'Upcoming')], default='upcoming', max_length=8),
        ),
    ]
