# Generated by Django 4.1.3 on 2022-12-27 11:32

from django.db import migrations
import requests
import urllib3

requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS = "ALL:@SECLEVEL=1"


def get_classes_from_PW_populate(apps, schema_editor):
    Project = apps.get_model("infraohjelmointi_api", "Project")
    projects = Project.objects.exclude(hkrId=None)
    session = requests.Session()
    session.auth = ("UZAIRAHMED", "Bum8E6l8LibQRH")
    for project in projects:
        response = session.get(
            "https://prokkis.hel.fi/ws/v2.8/repositories/Bentley.PW--HELS000601.helsinki1.hki.local~3APWHKIKOUL/PW_WSG_Dynamic/PrType_1121_HKR_Hankerek_Hanke?$filter=PROJECT_HKRHanketunnus+eq+{}".format(
                project.hkrId
            )
        )
        if len(response.json()["instances"]) > 0:
            projectProperties = response.json()["instances"][0]["properties"]
            print(
                "\n Project Name: {}, Masterclass: {}, Class: {}, SubClass: {}".format(
                    projectProperties["PROJECT_Kadun_tai_puiston_nimi"],
                    projectProperties["PROJECT_Pluokka"],
                    projectProperties["PROJECT_Luokka"],
                    projectProperties["PROJECT_Alaluokka"],
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0020_auto_project_classes_populate"),
    ]

    operations = [migrations.RunPython(get_classes_from_PW_populate)]
