# Generated by Django 4.1.3 on 2022-11-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0020_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='personConstruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='construction', to='infraohjelmointi_api.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personPlanning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planning', to='infraohjelmointi_api.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personProgramming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programming', to='infraohjelmointi_api.person'),
        ),
    ]
