# Generated by Django 4.1.3 on 2022-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0020_projectlocation_project_projectlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnote",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
