# Generated by Django 4.1.3 on 2023-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0024_redefine_project_hashtags_and_create_hashtags_table",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="entityName",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
