# Generated by Django 4.1.3 on 2023-01-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0025_alter_project_entityname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
