# Generated by Django 4.1.3 on 2023-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infraohjelmointi_api",
            "0028_projectgroup_model_creation_field_addition_project",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="otherPersons",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
