# Generated by Django 4.1.3 on 2023-02-09 13:55

from django.db import migrations


def set_project_locked_conditionally(apps, schema_editor):
    Project = apps.get_model("infraohjelmointi_api", "Project")
    Project.objects.filter(phase__value="construction").update(locked=True)


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0029_project_otherpersons"),
    ]

    operations = [
        migrations.RunPython(set_project_locked_conditionally),
    ]
