# Generated by Django 4.1.3 on 2023-02-16 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0029_project_otherpersons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='locked',
        ),
        migrations.CreateModel(
            name='ProjectLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lockType', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('lockedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.person')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lockRecord', to='infraohjelmointi_api.project')),
            ],
        ),
    ]
