# Generated by Django 4.1.3 on 2023-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0030_remove_project_locked_create_projectlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budgetProposalCurrentYearPlus0',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
