# Generated by Django 4.1.3 on 2023-03-29 13:59

from django.db import migrations, models
import django.db.models.deletion
import infraohjelmointi_api.models.Project


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0031_project_budgetproposalcurrentyearplus0_and_description_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(blank=True, default=infraohjelmointi_api.models.Project.get_default_projectPhase, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectphase'),
        ),
    ]
