# Generated by Django 4.1.3 on 2023-03-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "infraohjelmointi_api",
            "0032_remove_project_budgetproposalcurrentyearplus0_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectclass",
            name="forCoordinatorOnly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectclass",
            name="relatedTo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectclass",
            ),
        ),
        migrations.AddField(
            model_name="projectlocation",
            name="parentClass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectclass",
            ),
        ),
        migrations.AddField(
            model_name="projectlocation",
            name="forCoordinatorOnly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectlocation",
            name="relatedTo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectlocation",
            ),
        ),
    ]
