# Generated by Django 4.1.3 on 2023-03-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0032_projectclass_forcoordinatoronly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlocation',
            name='forCoordinatorOnly',
            field=models.BooleanField(default=False),
        ),
    ]
