# Generated by Django 4.1.3 on 2023-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0033_forcoordinatoronly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pwGUID",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
