# Generated by Django 4.1.3 on 2023-06-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0034_remove_projectgroup_unique together constraint project group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinancial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='infraohjelmointi_api.project'),
        ),
    ]
