# Generated by Django 4.1.3 on 2023-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0034_remove_projectgroup_unique together constraint project group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pwInstanceId',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
