# Generated by Django 4.1.3 on 2023-03-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0034_projectclass_relatedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlocation',
            name='relatedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectlocation'),
        ),
    ]
