# Generated by Django 4.1.3 on 2023-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0035_alter_projectfinancial_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfinancial",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        )
    ]
