# Generated by Django 4.1.3 on 2023-06-29 08:57

from django.db import migrations, models


def move_finance_data_to_new_structure(apps, schema_editor):
    ProjectFinancial = apps.get_model("infraohjelmointi_api", "ProjectFinancial")

    def getYearToFieldMapping(financeObject):
        return {
            financeObject.year: financeObject.budgetProposalCurrentYearPlus0,
            financeObject.year + 1: financeObject.budgetProposalCurrentYearPlus1,
            financeObject.year + 2: financeObject.budgetProposalCurrentYearPlus2,
            financeObject.year + 3: financeObject.preliminaryCurrentYearPlus3,
            financeObject.year + 4: financeObject.preliminaryCurrentYearPlus4,
            financeObject.year + 5: financeObject.preliminaryCurrentYearPlus5,
            financeObject.year + 6: financeObject.preliminaryCurrentYearPlus6,
            financeObject.year + 7: financeObject.preliminaryCurrentYearPlus7,
            financeObject.year + 8: financeObject.preliminaryCurrentYearPlus8,
            financeObject.year + 9: financeObject.preliminaryCurrentYearPlus9,
            financeObject.year + 10: financeObject.preliminaryCurrentYearPlus10,
        }

    allFinancialsQuerySet = ProjectFinancial.objects.all()
    for financeObject in allFinancialsQuerySet:
        # get year and related field, make a new row or update existing
        # get all + 10 related fields and make a new row or update it
        yearToFields = getYearToFieldMapping(financeObject)
        for year in yearToFields:
            ProjectFinancial.objects.update_or_create(
                project=financeObject.project,
                year=year,
                defaults={"value": yearToFields[year]},
            )


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0035_alter_projectfinancial_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfinancial",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=20, null=True
            ),
        ),
        migrations.RunPython(move_finance_data_to_new_structure),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="budgetProposalCurrentYearPlus0",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="budgetProposalCurrentYearPlus1",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="budgetProposalCurrentYearPlus2",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus10",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus3",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus4",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus5",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus6",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus7",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus8",
        ),
        migrations.RemoveField(
            model_name="projectfinancial",
            name="preliminaryCurrentYearPlus9",
        ),
    ]
