# Generated by Django 4.1.3 on 2023-05-23 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import infraohjelmointi_api.models.Project
from django.db.models import Q


def update_altered_field_to_new_defaults(apps, schema_editor):
    Project = apps.get_model("infraohjelmointi_api", "Project")
    Project.objects.filter(
        Q(planningStartYear=0) | Q(budgetOverrunYear=0) | Q(constructionEndYear=0)
    ).update(planningStartYear=None, budgetOverrunYear=None, constructionEndYear=None)
    Project.objects.filter(phase=None).update(
        phase=infraohjelmointi_api.models.Project.get_default_projectPhase()
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "infraohjelmointi_api",
            "0038_remove_old_financial_fields_project_financials",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budgetOverrunYear",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="constructionEndYear",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                default=infraohjelmointi_api.models.Project.get_default_projectPhase,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectphase",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="planningStartYear",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="projectphase",
            constraint=models.UniqueConstraint(
                fields=("value",), name="Unique constraint ProjectPhase"
            ),
        ),
        migrations.RunPython(update_altered_field_to_new_defaults),
    ]
