# Generated by Django 4.1.3 on 2023-07-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0039_alter_project_budgetoverrunyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclass',
            name='relatedTo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinatorClass', to='infraohjelmointi_api.projectclass'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='relatedTo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coordinatorLocation', to='infraohjelmointi_api.projectlocation'),
        ),
    ]
