# Generated by Django 4.1.3 on 2023-08-02 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import infraohjelmointi_api.models.ClassFinancial
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0040_alter_projectclass_relatedto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFinancial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=infraohjelmointi_api.models.ClassFinancial.ClassFinancial.currentYear, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('frameBudget', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('classRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='infraohjelmointi_api.projectclass')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classfinancial',
            constraint=models.UniqueConstraint(fields=('classRelation', 'year'), name='Unique together Constraint Class Financial'),
        ),
        migrations.AddConstraint(
            model_name='classfinancial',
            constraint=models.CheckConstraint(check=models.Q(('classRelation__forCoordinatorOnly', False)), name='Planning class only foreign key constraint'),
        ),
    ]
