# Generated by Django 4.1.3 on 2023-08-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0041_classfinancial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthashtag',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projecthashtag',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
