# Generated by Django 4.1.3 on 2023-09-01 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import infraohjelmointi_api.models.LocationFinancial
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "infraohjelmointi_api",
            "0042_projecthashtag_archived_alter_projecthashtag_value",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationFinancial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=infraohjelmointi_api.models.LocationFinancial.currentYear,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3000),
                        ],
                    ),
                ),
                (
                    "frameBudget",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "budgetChange",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "locationRelation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finances",
                        to="infraohjelmointi_api.projectlocation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="locationfinancial",
            constraint=models.UniqueConstraint(
                fields=("locationRelation", "year"),
                name="Unique together Constraint Location Financial",
            ),
        ),
    ]
