# Generated by Django 4.1.3 on 2023-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0043_locationfinancial_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectfinancial",
            name="Unique together Constraint Project Financial",
        ),
        migrations.AddField(
            model_name="project",
            name="frameEstConstructionEnd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="frameEstConstructionStart",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="frameEstPlanningEnd",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="frameEstPlanningStart",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectfinancial",
            name="forFrameView",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="projectfinancial",
            constraint=models.UniqueConstraint(
                fields=("project", "year", "forFrameView"),
                name="Unique together Constraint Project Financial",
            ),
        ),
    ]
