# Generated by Django 4.1.3 on 2023-08-29 07:58

from django.db import migrations
from django.db.models import F


def copy_project_finances_to_frame(apps, schema_editor):
    ProjectFinancial = apps.get_model("infraohjelmointi_api", "ProjectFinancial")
    Project = apps.get_model("infraohjelmointi_api", "Project")
    # id=None copies all the fields and performs an insert
    frameProjectFinances = []
    for projectFinancial in ProjectFinancial.objects.all():
        projectFinancial.id = None
        projectFinancial.forFrameView = True
        frameProjectFinances.append(projectFinancial)

    ProjectFinancial.objects.bulk_create(frameProjectFinances)

    Project.objects.filter(
        estPlanningStart__isnull=False,
        estPlanningEnd__isnull=False,
        estConstructionStart__isnull=False,
        estConstructionEnd__isnull=False,
    ).update(
        frameEstPlanningStart=F("estPlanningStart"),
        frameEstPlanningEnd=F("estPlanningEnd"),
        frameEstConstructionStart=F("estConstructionStart"),
        frameEstConstructionEnd=F("estConstructionEnd"),
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "infraohjelmointi_api",
            "0044_remove_projectfinancial_unique together constraint project financial_and_more",
        ),
    ]

    operations = [migrations.RunPython(copy_project_finances_to_frame)]
