# Generated by Django 4.1.3 on 2023-09-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0045_auto_project_finances_to_frame_finances'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclass',
            name='relatedLocation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatedCoordinatorClass', to='infraohjelmointi_api.projectlocation'),
        ),
    ]
