# Generated by Django 4.1.3 on 2023-09-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0046_projectclass_relatedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.person'),
        ),
    ]
