# Generated by Django 4.1.3 on 2023-09-22 08:57

from django.db import migrations


def set_existing_note_updatedBy_null(apps, schema_editor):
    Note = apps.get_model("infraohjelmointi_api", "Note")
    Note.objects.all().update(updatedBy=None)


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0048_sapcost"),
    ]

    operations = [migrations.RunPython(set_existing_note_updatedBy_null)]
