# Generated by Django 4.1.3 on 2023-10-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0050_remove_historicalnote_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfinancial',
            name='budgetChange',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='locationfinancial',
            name='budgetChange',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
