# Generated by Django 4.1.3 on 2023-10-20 05:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0051_alter_classfinancial_budgetchange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coordinatorNote', models.TextField(blank=True, default='')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)])),
                ('coordinatorClassName', models.CharField(max_length=150)),
                ('updatedByFirstName', models.CharField(max_length=50)),
                ('updatedByLastName', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('coordinatorClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectclass')),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
