# Generated by Django 4.1.3 on 2023-12-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0052_alter_project_favpersons_alter_project_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraohjelmointi_api.project'),
        ),
    ]
