# Generated by Django 4.1.3 on 2024-01-08 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0053_alter_note_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDistrict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=300)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='projectgroup',
            name='Unique together Constraint Project Group',
        ),
        migrations.AddField(
            model_name='projectdistrict',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childClass', to='infraohjelmointi_api.projectdistrict'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectDistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectdistrict'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectdistrict'),
        ),
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(fields=('name', 'location', 'locationRelation', 'classRelation'), name='Unique together Constraint Project Group'),
        ),
    ]
