# Generated by Django 4.2 on 2024-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0055_coordinatornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='costForecast',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
