# Generated by Django 4.2 on 2024-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0056_appstatevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfinancial',
            name='forFrameView',
            field=models.BooleanField(default=False),
        ),
    ]
