# Generated by Django 4.2 on 2024-11-05 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0056_alter_project_costforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStateValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='classfinancial',
            name='Unique together Constraint Class Financial',
        ),
        migrations.RemoveConstraint(
            model_name='locationfinancial',
            name='Unique together Constraint Location Financial',
        ),
        migrations.AddField(
            model_name='classfinancial',
            name='forFrameView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationfinancial',
            name='forFrameView',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='classfinancial',
            constraint=models.UniqueConstraint(fields=('classRelation', 'year', 'forFrameView'), name='Unique together Constraint Class Financial'),
        ),
        migrations.AddConstraint(
            model_name='locationfinancial',
            constraint=models.UniqueConstraint(fields=('locationRelation', 'year', 'forFrameView'), name='Unique together Constraint Location Financial'),
        ),
    ]
