# Generated by Django 4.2 on 2024-11-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0057_classfinancial_forframeview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classfinancial',
            name='Unique together Constraint Class Financial',
        ),
        migrations.AddConstraint(
            model_name='classfinancial',
            constraint=models.UniqueConstraint(fields=('classRelation', 'year', 'forFrameView'), name='Unique together Constraint Class Financial'),
        ),
    ]
