# Generated by Django 4.2 on 2024-12-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0058_sapcurrentyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapcost',
            name='year',
        ),
    ]
