# Generated by Django 4.2 on 2024-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0058_remove_classfinancial_unique_together_constraint_class_financial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfinancial',
            name='forFrameView',
            field=models.BooleanField(default=False),
        ),
    ]
