# Generated by Django 4.2 on 2024-11-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0059_locationfinancial_forframeview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationfinancial',
            name='Unique together Constraint Location Financial',
        ),
        migrations.AddConstraint(
            model_name='locationfinancial',
            constraint=models.UniqueConstraint(fields=('locationRelation', 'year', 'forFrameView'), name='Unique together Constraint Location Financial'),
        ),
    ]
