# Generated by Django 4.2 on 2025-01-02 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0059_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='endpoint',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='log_level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operation',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='origin',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.project'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='project_class',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectclass'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='project_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.projectgroup'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], editable=False, max_length=20),
        ),
    ]
