# Generated by Django 4.2.17 on 2025-04-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0062_alter_auditlog_project_alter_auditlog_project_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estWarrantyPhaseEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estWarrantyPhaseStart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frameEstWarrantyPhaseEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frameEstWarrantyPhaseStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
