# Generated by Django 4.2.17 on 2025-04-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0065_data_for_budget_overrun_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budgetOverrunReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.budgetoverrunreason'),
        ),
        migrations.AddField(
            model_name='project',
            name='otherBudgetOverrunReason',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
