# Generated by Django 4.2.22 on 2025-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0066_project_budgetoverrunreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_api_use',
            field=models.DateField(blank=True, null=True, verbose_name='Latest API token usage date'),
        ),
    ]
