# Generated by Django 4.2.22 on 2025-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0067_user_last_api_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onSchedule',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
