# Generated by Django 4.2.22 on 2025-09-02 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0067_user_last_api_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgrammer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personProgramming', to='infraohjelmointi_api.person')),
            ],
        ),
        migrations.AddField(
            model_name='projectclass',
            name='defaultProgrammer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='infraohjelmointi_api.projectprogrammer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personProgramming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programming', to='infraohjelmointi_api.projectprogrammer'),
        ),
    ]
