# Generated by Django 4.2.22 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0069_create_empty_programmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onSchedule',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
