# Generated by Django 4.2.24 on 2025-10-29 13:43

from django.db import migrations


def update_project_location(apps, schema_editor):
    ProjectLocation = apps.get_model('infraohjelmointi_api', 'ProjectLocation')
    # Fix the name and path for Oulunkylä
    ProjectLocation.objects.filter(
        name='28. Oulukylä'
    ).update(name='28. Oulunkylä', path='Pohjoinen/Oulunkylä')


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0071_add_additional_budget_overrun_reasons'),
    ]

    operations = [
        migrations.RunPython(update_project_location, migrations.RunPython.noop),
    ]
