# Generated by Django 4.2.24 on 2025-11-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0073_fix_completed_projects_programmed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectprogrammer',
            unique_together={('firstName', 'lastName')},
        ),
    ]
