# Generated by Django 4.2.24 on 2025-11-17 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0073_fix_completed_projects_programmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalpaAssetClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('componentClass', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('holdingPeriodYears', models.PositiveIntegerField(blank=True, null=True)),
                ('hasHoldingPeriod', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['componentClass'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectNumberRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectTypePrefix', models.CharField(choices=[('2814I', '2814I - Infrastructure Investment'), ('2814E', '2814E - Pre-construction')], max_length=10)),
                ('budgetAccount', models.CharField(blank=True, max_length=50, null=True)),
                ('budgetAccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('rangeStart', models.CharField(max_length=20)),
                ('rangeEnd', models.CharField(max_length=20)),
                ('majorDistrict', models.CharField(blank=True, max_length=10, null=True)),
                ('majorDistrictName', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Tontit', 'Tontit - Plots'), ('Mao', 'Mao - Land Use'), ('Geo', 'Geo - Geotechnical')], max_length=50, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=200, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('transferNote', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['projectTypePrefix', 'budgetAccount', 'rangeStart'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('excel_generated', 'Avauspyyntö-Excel muodostettu'), ('sent_to_talpa', 'Avauspyyntö lähetetty Talpaan'), ('project_number_opened', 'Projektinumero avattu')], default='excel_generated', max_length=50)),
                ('servicePackage', models.CharField(default='Taloushallinnon palvelut', max_length=100)),
                ('service', models.CharField(default='SAP-projektinumeron avauspyyntö', max_length=100)),
                ('priority', models.CharField(choices=[('Normaali', 'Normaali - Normal'), ('Korkea', 'Korkea - High')], max_length=20)),
                ('subject', models.CharField(choices=[('Uusi', 'Uusi - New'), ('Muutos', 'Muutos - Change'), ('Lukitus', 'Lukitus - Lock')], max_length=20)),
                ('organization', models.CharField(default='2800 Kymp', max_length=50)),
                ('additionalInformation', models.TextField(blank=True, null=True)),
                ('projectName', models.CharField(blank=True, max_length=200, null=True)),
                ('budgetAccount', models.CharField(blank=True, max_length=50, null=True)),
                ('majorDistrict', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('projectNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('projectDescription', models.TextField(blank=True, null=True)),
                ('responsiblePerson', models.CharField(blank=True, max_length=200, null=True)),
                ('responsiblePersonEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('responsiblePersonPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('excelFile', models.FileField(blank=True, null=True, upload_to='talpa_excel/')),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('investmentProfile', models.CharField(blank=True, max_length=50, null=True)),
                ('profileName', models.CharField(blank=True, max_length=200, null=True)),
                ('templateProject', models.CharField(blank=True, max_length=50, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validityYear', models.PositiveIntegerField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TalpaServiceClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('projectTypePrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='talpaserviceclass',
            constraint=models.UniqueConstraint(fields=('code',), name='Unique constraint TalpaServiceClass code'),
        ),
        migrations.AddConstraint(
            model_name='talpaprojecttype',
            constraint=models.UniqueConstraint(fields=('code',), name='Unique constraint TalpaProjectType code'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='assetClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaassetclass'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='talpaProjectOpeningsCreated', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talpaProjectOpening', to='infraohjelmointi_api.project'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaprojecttype'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='serviceClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaserviceclass'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='updatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='talpaProjectOpeningsUpdated', to='infraohjelmointi_api.person'),
        ),
        migrations.AddConstraint(
            model_name='talpaassetclass',
            constraint=models.UniqueConstraint(fields=('componentClass', 'account'), name='Unique constraint TalpaAssetClass componentClass account'),
        ),
    ]
