# Generated by Django 4.2.24 on 2025-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0074_talpaassetclass_talpaprojectnumberrange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talpaprojectopening',
            name='postalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='readiness',
            field=models.CharField(blank=True, choices=[('Kesken', 'Kesken - In Progress'), ('Valmis', 'Valmis - Ready')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='projectName',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='unit',
            field=models.CharField(blank=True, choices=[('Tontit', 'Tontit - Plots'), ('Mao', 'Mao - Land Use'), ('Geo', 'Geo - Geotechnical')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectprogrammer',
            unique_together={('firstName', 'lastName')},
        ),
    ]
