# Generated by Django 4.2.24 on 2025-11-21 14:19
# Modified to handle existing indexes from old 0075 migration

from django.db import migrations, models, connection


def create_indexes_safely(apps, schema_editor):
    """
    Create indexes using IF NOT EXISTS to handle cases where old 0075 migration already ran.
    This ensures the migration is safe whether indexes exist or not.
    """
    with connection.cursor() as cursor:
        # Get actual table names from Django
        ProjectClass = apps.get_model('infraohjelmointi_api', 'ProjectClass')
        ClassFinancial = apps.get_model('infraohjelmointi_api', 'ClassFinancial')
        Project = apps.get_model('infraohjelmointi_api', 'Project')
        ProjectFinancial = apps.get_model('infraohjelmointi_api', 'ProjectFinancial')
        ProjectLocation = apps.get_model('infraohjelmointi_api', 'ProjectLocation')
        
        indexes = [
            (ProjectClass._meta.db_table, 'idx_projectclass_parent', ProjectClass, ['parent']),
            (ProjectClass._meta.db_table, 'idx_projectclass_programmer', ProjectClass, ['defaultProgrammer']),
            (ProjectClass._meta.db_table, 'idx_projectclass_path', ProjectClass, ['path']),
            (ProjectClass._meta.db_table, 'idx_projectclass_coordinator', ProjectClass, ['forCoordinatorOnly']),
            (ClassFinancial._meta.db_table, 'idx_classfinancial_year', ClassFinancial, ['year']),
            (ClassFinancial._meta.db_table, 'idx_classfinancial_frameview', ClassFinancial, ['forFrameView']),
            (ClassFinancial._meta.db_table, 'idx_classfinancial_class', ClassFinancial, ['classRelation']),
            (ClassFinancial._meta.db_table, 'idx_classfinancial_composite', ClassFinancial, ['classRelation', 'year', 'forFrameView']),
            (Project._meta.db_table, 'idx_project_programmed', Project, ['programmed']),
            (Project._meta.db_table, 'idx_project_class', Project, ['projectClass']),
            (ProjectFinancial._meta.db_table, 'idx_projectfinancial_year', ProjectFinancial, ['year']),
            (ProjectFinancial._meta.db_table, 'idx_projectfinancial_frameview', ProjectFinancial, ['forFrameView']),
            (ProjectLocation._meta.db_table, 'idx_projectlocation_parent', ProjectLocation, ['parent']),
            (ProjectLocation._meta.db_table, 'idx_projloc_parentclass', ProjectLocation, ['parentClass']),
        ]
        
        for table_name, index_name, model, field_names in indexes:
            # Get actual database column names
            db_columns = []
            for field_name in field_names:
                field = model._meta.get_field(field_name)
                db_column = field.db_column or field.get_attname()
                db_columns.append(db_column)
            
            # Use CREATE INDEX IF NOT EXISTS for safety
            fields_str = ', '.join(f'"{col}"' for col in db_columns)
            cursor.execute(f'''
                CREATE INDEX IF NOT EXISTS "{index_name}" 
                ON "{table_name}" ({fields_str})
            ''')


def reverse_indexes(apps, schema_editor):
    """Drop indexes if they exist"""
    with connection.cursor() as cursor:
        indexes = [
            'idx_projectclass_parent',
            'idx_projectclass_programmer',
            'idx_projectclass_path',
            'idx_projectclass_coordinator',
            'idx_classfinancial_year',
            'idx_classfinancial_frameview',
            'idx_classfinancial_class',
            'idx_classfinancial_composite',
            'idx_project_programmed',
            'idx_project_class',
            'idx_projectfinancial_year',
            'idx_projectfinancial_frameview',
            'idx_projectlocation_parent',
            'idx_projloc_parentclass',
        ]
        for index_name in indexes:
            cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0074_alter_projectprogrammer_unique_together'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to:
        # 1. Safely create indexes in database (handles existing indexes from old 0075)
        # 2. Tell Django about the state change (so it tracks them properly)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_indexes_safely, reverse_indexes),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='classfinancial',
                    index=models.Index(fields=['year'], name='idx_classfinancial_year'),
                ),
                migrations.AddIndex(
                    model_name='classfinancial',
                    index=models.Index(fields=['forFrameView'], name='idx_classfinancial_frameview'),
                ),
                migrations.AddIndex(
                    model_name='classfinancial',
                    index=models.Index(fields=['classRelation'], name='idx_classfinancial_class'),
                ),
                migrations.AddIndex(
                    model_name='classfinancial',
                    index=models.Index(fields=['classRelation', 'year', 'forFrameView'], name='idx_classfinancial_composite'),
                ),
                migrations.AddIndex(
                    model_name='project',
                    index=models.Index(fields=['programmed'], name='idx_project_programmed'),
                ),
                migrations.AddIndex(
                    model_name='project',
                    index=models.Index(fields=['projectClass'], name='idx_project_class'),
                ),
                migrations.AddIndex(
                    model_name='projectclass',
                    index=models.Index(fields=['parent'], name='idx_projectclass_parent'),
                ),
                migrations.AddIndex(
                    model_name='projectclass',
                    index=models.Index(fields=['defaultProgrammer'], name='idx_projectclass_programmer'),
                ),
                migrations.AddIndex(
                    model_name='projectclass',
                    index=models.Index(fields=['path'], name='idx_projectclass_path'),
                ),
                migrations.AddIndex(
                    model_name='projectclass',
                    index=models.Index(fields=['forCoordinatorOnly'], name='idx_projectclass_coordinator'),
                ),
                migrations.AddIndex(
                    model_name='projectfinancial',
                    index=models.Index(fields=['year'], name='idx_projectfinancial_year'),
                ),
                migrations.AddIndex(
                    model_name='projectfinancial',
                    index=models.Index(fields=['forFrameView'], name='idx_projectfinancial_frameview'),
                ),
                migrations.AddIndex(
                    model_name='projectlocation',
                    index=models.Index(fields=['parent'], name='idx_projectlocation_parent'),
                ),
                migrations.AddIndex(
                    model_name='projectlocation',
                    index=models.Index(fields=['parentClass'], name='idx_projloc_parentclass'),
                ),
            ],
        ),
    ]
