# Generated by Django 4.2.26 on 2025-12-02 15:47
# Modified to handle last_api_use field removal idempotently

from django.db import migrations, models, connection
import django.db.models.deletion
import uuid


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s 
                AND column_name = %s
            );
        """, [table_name, column_name])
        return cursor.fetchone()[0]


class SkipRemoveFieldIfNotExists(migrations.operations.fields.RemoveField):
    """RemoveField operation that skips if field doesn't exist in database, but always updates state"""

    def state_forwards(self, app_label, state):
        """Always try to remove from state if it exists (idempotent)"""
        model_name_lower = self.model_name.lower()
        model_key = (app_label, model_name_lower)
        model_state = state.models.get(model_key)
        if model_state and self.name in model_state.fields:
            # Field exists in state, remove it
            super().state_forwards(app_label, state)
        # If field doesn't exist in state, that's fine - state is already correct

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Update database, but skip if column doesn't exist"""
        table_name = f"{app_label}_{self.model_name.lower()}"
        column_name = self.name

        if not column_exists(table_name, column_name):
            # Column doesn't exist in database, skip removal
            return

        # Column exists, remove it
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0075_classfinancial_idx_classfinancial_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalpaAssetClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('componentClass', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('holdingPeriodYears', models.PositiveIntegerField(blank=True, null=True)),
                ('hasHoldingPeriod', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['componentClass'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectNumberRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectTypePrefix', models.CharField(choices=[('2814I', '2814I - Infrastructure Investment'), ('2814E', '2814E - Pre-construction')], max_length=10)),
                ('budgetAccount', models.CharField(blank=True, max_length=50, null=True)),
                ('budgetAccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('rangeStart', models.CharField(max_length=20)),
                ('rangeEnd', models.CharField(max_length=20)),
                ('majorDistrict', models.CharField(blank=True, max_length=10, null=True)),
                ('majorDistrictName', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Tontit', 'Tontit - Plots'), ('Mao', 'Mao - Land Use'), ('Geo', 'Geo - Geotechnical')], max_length=50, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=200, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('transferNote', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['projectTypePrefix', 'budgetAccount', 'rangeStart'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('excel_generated', 'Avauspyyntö-Excel muodostettu'), ('sent_to_talpa', 'Avauspyyntö lähetetty Talpaan'), ('project_number_opened', 'Projektinumero avattu')], default='excel_generated', max_length=50)),
                ('servicePackage', models.CharField(default='Taloushallinnon palvelut', max_length=100)),
                ('service', models.CharField(default='SAP-projektinumeron avauspyyntö', max_length=100)),
                ('priority', models.CharField(choices=[('Normaali', 'Normaali - Normal'), ('Korkea', 'Korkea - High')], default='Normaali', max_length=20)),
                ('subject', models.CharField(choices=[('Uusi', 'Uusi - New'), ('Muutos', 'Muutos - Change'), ('Lukitus', 'Lukitus - Lock')], max_length=20)),
                ('organization', models.CharField(default='2800 Kymp', max_length=50)),
                ('additionalInformation', models.TextField(blank=True, null=True)),
                ('projectName', models.CharField(blank=True, max_length=24, null=True)),
                ('budgetAccount', models.CharField(blank=True, max_length=50, null=True)),
                ('majorDistrict', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('projectStartDate', models.DateField(blank=True, null=True)),
                ('projectEndDate', models.DateField(blank=True, null=True)),
                ('responsiblePerson', models.CharField(blank=True, max_length=200, null=True)),
                ('responsiblePersonEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('excelFile', models.FileField(blank=True, null=True, upload_to='talpa_excel/')),
                ('projectDescription', models.TextField(blank=True, null=True)),
                ('responsiblePersonPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Tontit', 'Tontit - Plots'), ('Mao', 'Mao - Land Use'), ('Geo', 'Geo - Geotechnical')], max_length=50, null=True)),
                ('investmentProfile', models.CharField(blank=True, max_length=50, null=True)),
                ('profileName', models.CharField(blank=True, max_length=200, null=True)),
                ('templateProject', models.CharField(blank=True, max_length=50, null=True)),
                ('readiness', models.CharField(blank=True, choices=[('Kesken', 'Kesken - In Progress'), ('Valmis', 'Valmis - Ready')], max_length=50, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='TalpaProjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validityYear', models.PositiveIntegerField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TalpaServiceClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('projectTypePrefix', models.CharField(blank=True, max_length=10, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        SkipRemoveFieldIfNotExists(
            model_name='user',
            name='last_api_use',
        ),
        migrations.AddConstraint(
            model_name='talpaserviceclass',
            constraint=models.UniqueConstraint(fields=('code',), name='Unique constraint TalpaServiceClass code'),
        ),
        migrations.AddConstraint(
            model_name='talpaprojecttype',
            constraint=models.UniqueConstraint(fields=('code', 'priority'), name='Unique constraint TalpaProjectType code and priority'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='assetClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaassetclass'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='talpaProjectOpeningsCreated', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talpaProjectOpening', to='infraohjelmointi_api.project'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectNumberRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaprojectnumberrange'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaprojecttype'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='serviceClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaserviceclass'),
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='updatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='talpaProjectOpeningsUpdated', to='infraohjelmointi_api.person'),
        ),
        migrations.AddConstraint(
            model_name='talpaassetclass',
            constraint=models.UniqueConstraint(fields=('componentClass', 'account'), name='Unique constraint TalpaAssetClass componentClass account'),
        ),
    ]
