# Generated by Django 4.2.24 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0075_talpaprojectopening_postalcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talpaprojecttype',
            options={'ordering': ['code', 'priority']},
        ),
        migrations.RemoveConstraint(
            model_name='talpaprojecttype',
            name='Unique constraint TalpaProjectType code',
        ),
        migrations.AddConstraint(
            model_name='talpaprojecttype',
            constraint=models.UniqueConstraint(fields=('code', 'priority'), name='Unique constraint TalpaProjectType code and priority'),
        ),
    ]
