# Generated by Django 4.2.24 on 2025-11-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0076_alter_talpaprojecttype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talpaprojectopening',
            name='projectNumber',
        ),
        migrations.AddField(
            model_name='talpaprojectopening',
            name='projectNumberRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.talpaprojectnumberrange'),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='priority',
            field=models.CharField(choices=[('Normaali', 'Normaali - Normal'), ('Korkea', 'Korkea - High')], default='Normaali', max_length=20),
        ),
    ]
