# Generated by Django 4.2.26 on 2025-12-05 17:14
# Migration for IO-756: Restricted Programmer Permissions Fix
# Creates ClassProgrammerAssignment model for direct User→ProjectClass assignments
# Made idempotent: checks if table exists before creating (handles case where old 0076 was already applied)

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import uuid


def table_exists(table_name):
    """Check if a table exists in the database"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


class CreateModelIfNotExists(migrations.operations.models.CreateModel):
    """CreateModel operation that skips if table already exists"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Get the model from the new state to determine table name
        model_state = to_state.models[(app_label, self.name.lower())]
        # Use the model's db_table if specified, otherwise generate it
        table_name = model_state.options.get('db_table') or f"{app_label}_{self.name.lower()}"
        
        if table_exists(table_name):
            # Table already exists, skip DB operation
            # State is updated by parent's state_forwards which is called automatically
            return
        
        # Table doesn't exist, create it
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0077_fix_user_last_api_use_state'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='ClassProgrammerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project_class', models.ForeignKey(help_text='The project class this user can edit', on_delete=django.db.models.deletion.CASCADE, related_name='programmer_assignments', to='infraohjelmointi_api.projectclass')),
                ('user', models.ForeignKey(help_text='The user who can edit projects in this class', on_delete=django.db.models.deletion.CASCADE, related_name='class_programmer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Programmer Assignment',
                'verbose_name_plural': 'Class Programmer Assignments',
                'indexes': [models.Index(fields=['user'], name='idx_cpa_user'), models.Index(fields=['project_class'], name='idx_cpa_class')],
                'unique_together': {('user', 'project_class')},
            },
        ),
    ]
