# Generated by Django 4.2.26 on 2025-12-11 19:20
# Modified to ensure last_api_use field exists in both state and database (idempotent)

from django.db import migrations, models


def column_exists(table_name, column_name, schema_editor):
    """Check if a column exists in a table"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = %s 
                AND column_name = %s
            );
        """, [table_name, column_name])
        return cursor.fetchone()[0]


class AddFieldIfNotExists(migrations.operations.fields.AddField):
    """AddField that is idempotent for both state and database"""
    
    def state_forwards(self, app_label, state):
        model_name_lower = self.model_name.lower()
        model_key = (app_label, model_name_lower)
        model_state = state.models.get(model_key)
        
        if model_state and self.name in model_state.fields:
            return
        
        super().state_forwards(app_label, state)
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        table_name = f"{app_label}_{self.model_name.lower()}"
        column_name = self.name
        
        if column_exists(table_name, column_name, schema_editor):
            return
        
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AlterFieldIfExists(migrations.operations.fields.AlterField):
    """AlterField that is idempotent - only alters if field exists in state"""
    
    def state_forwards(self, app_label, state):
        model_name_lower = self.model_name.lower()
        model_key = (app_label, model_name_lower)
        model_state = state.models.get(model_key)
        
        if not model_state or self.name not in model_state.fields:
            return
        
        super().state_forwards(app_label, state)
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        table_name = f"{app_label}_{self.model_name.lower()}"
        column_name = self.name
        
        if not column_exists(table_name, column_name, schema_editor):
            return
        
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def ensure_last_api_use_column(apps, schema_editor):
    """Safety check: ensure column exists in database"""
    table_name = 'infraohjelmointi_api_user'
    column_name = 'last_api_use'
    
    if column_exists(table_name, column_name, schema_editor):
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"""
            ALTER TABLE "{table_name}" 
            ADD COLUMN "{column_name}" DATE NULL;
        """)


def reverse_ensure_last_api_use_column(apps, schema_editor):
    """Remove column if it exists"""
    table_name = 'infraohjelmointi_api_user'
    column_name = 'last_api_use'
    
    if not column_exists(table_name, column_name, schema_editor):
        return
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"""
            ALTER TABLE "{table_name}" 
            DROP COLUMN "{column_name}";
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0078_classprogrammerassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        AddFieldIfNotExists(
            model_name='user',
            name='last_api_use',
            field=models.DateField(blank=True, editable=False, help_text='Unused field - kept for database compatibility', null=True, verbose_name='Latest API token usage date'),
        ),
        migrations.RunPython(
            ensure_last_api_use_column,
            reverse_ensure_last_api_use_column,
        ),
        AlterFieldIfExists(
            model_name='user',
            name='last_api_use',
            field=models.DateField(blank=True, editable=False, help_text='Unused field - kept for database compatibility', null=True, verbose_name='Latest API token usage date'),
        ),
    ]
