# Generated by Django 4.2.26 on 2025-12-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0079_alter_user_options_alter_user_last_api_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='assetClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraohjelmointi_api.talpaassetclass'),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='projectNumberRange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraohjelmointi_api.talpaprojectnumberrange'),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='projectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraohjelmointi_api.talpaprojecttype'),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='serviceClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraohjelmointi_api.talpaserviceclass'),
        ),
    ]
