# Generated by Django 4.2.26 on 2025-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0080_alter_talpaprojectopening_assetclass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talpaprojecttype',
            options={'ordering': ['category', 'sortOrder', 'priority']},
        ),
        migrations.AddField(
            model_name='talpaprojecttype',
            name='sortOrder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
