# Generated by Django 4.2.26 on 2026-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0087_merge_construction_procurement_project_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetoverrunreason',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='constructionphase',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='constructionphasedetail',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='constructionprocurementmethod',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='planningphase',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='projectprogrammer',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='projectqualitylevel',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='responsiblezone',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='budgetoverrunreason',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionphasedetail',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionprocurementmethod',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planningphase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectprogrammer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectqualitylevel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='responsiblezone',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
