# Generated by Django 4.2.26 on 2026-01-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0088_update_talpa_project_range_area_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talpaprojectnumberrange',
            name='budgetAccount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='talpaprojectopening',
            name='budgetAccount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
