# Generated by Django 4.2.26 on 2026-02-25 06:59

from django.db import migrations

def set_initial_order(apps, schema_editor):
    budgetoverrunreason = apps.get_model("infraohjelmointi_api", "budgetoverrunreason")
    constructionphase = apps.get_model("infraohjelmointi_api", "constructionphase")
    constructionphasedetail = apps.get_model("infraohjelmointi_api", "constructionphasedetail")
    constructionprocurementmethod = apps.get_model("infraohjelmointi_api", "constructionprocurementmethod")
    planningphase = apps.get_model("infraohjelmointi_api", "planningphase")
    projectcategory = apps.get_model("infraohjelmointi_api", "projectcategory")
    projectphase = apps.get_model("infraohjelmointi_api", "projectphase")
    projectprogrammer = apps.get_model("infraohjelmointi_api", "projectprogrammer")
    projectqualitylevel = apps.get_model("infraohjelmointi_api", "projectqualitylevel")
    projecttype = apps.get_model("infraohjelmointi_api", "projecttype")
    responsiblezone = apps.get_model("infraohjelmointi_api", "responsiblezone")

    for Model in [budgetoverrunreason, constructionphase, constructionphasedetail, constructionprocurementmethod, planningphase, projectcategory, projectphase, projectprogrammer, projectqualitylevel, projecttype, responsiblezone]:
        for index, obj in enumerate(Model.objects.all()):
            obj.order = index
            obj.save(update_fields=["order"])

class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0088_alter_budgetoverrunreason_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_initial_order),
    ]
