# Generated by Django 4.1.3 on 2026-01-28 00:00

import django.db.models.deletion
from django.db import migrations, models
import infraohjelmointi_api.models.Project


def set_existing_priorities(apps, schema_editor):
    Project = apps.get_model("infraohjelmointi_api", "Project")
    ProjectPriority = apps.get_model("infraohjelmointi_api", "ProjectPriority")

    default_priority = ProjectPriority.objects.filter(value__iexact="medium").first()
    if default_priority is None:
        default_priority = ProjectPriority.objects.create(value="medium")

    Project.objects.filter(priority__isnull=True).update(priority=default_priority)


class Migration(migrations.Migration):
    dependencies = [
        ("infraohjelmointi_api", "0090_update_construction_procurement_method_kilpailutus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                default=infraohjelmointi_api.models.Project.get_default_projectPriority,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="infraohjelmointi_api.projectpriority",
            ),
        ),
        migrations.RunPython(set_existing_priorities, migrations.RunPython.noop),
    ]
