# Generated by Django 4.2.26 on 2026-03-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0089_alter_budgetoverrunreason_options_and_more'),
        ('infraohjelmointi_api', '0091_project_priority_default'),
    ]

    operations = [
    ]
