# Generated by Django 4.2.26 on 2026-03-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0092_add_itakeskus_project_classes'),
        ('infraohjelmointi_api', '0092_project_otherpersons_to_m2m'),
    ]

    operations = [
    ]
