# Generated by Django 4.2.26 on 2026-03-19 06:56

from django.db import migrations

def populate_stara_procurement_reason(apps, schema_editor):
    StaraProcurementReason = apps.get_model('infraohjelmointi_api', 'StaraProcurementReason')

    values = [
        "flexibleWork",
        "smallWork",
        "urgentWork",
        "difficultTenderableWork",
    ]

    for v in values:
        StaraProcurementReason.objects.get_or_create(value=v)


def reverse_populate_stara_procurement_reason(apps, schema_editor):
    StaraProcurementReason = apps.get_model('infraohjelmointi_api', 'StaraProcurementReason')
    StaraProcurementReason.objects.filter(value__in=[
        "flexibleWork",
        "smallWork",
        "urgentWork",
        "difficultTenderableWork",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0094_staraprocurementreason_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_stara_procurement_reason, reverse_populate_stara_procurement_reason),
    ]

