# Generated by Django 4.2.26 on 2026-03-23 11:57

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    models_to_fix = [
        "BudgetoverrunReason",
        "ConstructionPhase",
        "ConstructionPhaseDetail",
        "ConstructionProcurementMethod",
        "PlanningPhase",
        "ProjectCategory",
        "ProjectPhase",
        "ProjectProgrammer",
        "ProjectQualityLevel",
        "ProjectType",
        "ResponsibleZone",
    ]

    for model_name in models_to_fix:
        Model = apps.get_model("infraohjelmointi_api", model_name)

        items = Model.objects.all().order_by("createdDate", "id")

        for index, item in enumerate(items):
            item.order = index
            item.save(update_fields=["order"])

class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0095_auto_20260319_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetoverrunreason',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='constructionphase',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='constructionphasedetail',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='constructionprocurementmethod',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='planningphase',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projectqualitylevel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='responsiblezone',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='budgetoverrunreason',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='constructionphasedetail',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='constructionprocurementmethod',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='planningphase',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='projectphase',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='projectprogrammer',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='projectqualitylevel',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='projecttype',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='responsiblezone',
            name='order',
            field=models.IntegerField(null=True, blank=True)
        ),

        migrations.RunPython(set_initial_order),
    ]
