# Generated by Django 4.2.26 on 2026-03-26 08:11


from django.db import migrations


def update_construction_procurement_method_value(apps, schema_editor):
    ConstructionProcurementMethod = apps.get_model("infraohjelmointi_api", "ConstructionProcurementMethod")
    Project = apps.get_model("infraohjelmointi_api", "Project")

    try:
        removable_value_puitesopimus = ConstructionProcurementMethod.objects.get(value="Puitesopimus")
    except ConstructionProcurementMethod.DoesNotExist:
        removable_value_puitesopimus = None

    if removable_value_puitesopimus:
        Project.objects.filter(constructionProcurementMethod=removable_value_puitesopimus).update(constructionProcurementMethod=None)
        removable_value_puitesopimus.delete()

    new_values = [
        "frameAgreementMidSized",
        "frameAgreementSmall",
        "frameAgreementGreenery",
        "frameAgreementSportSite",
        "directProcurement",
    ]

    for val in new_values:
        ConstructionProcurementMethod.objects.get_or_create(value=val)


def reverse_update_construction_procurement_method_value(apps, schema_editor):
    ConstructionProcurementMethod = apps.get_model("infraohjelmointi_api", "ConstructionProcurementMethod")
    Project = apps.get_model("infraohjelmointi_api", "Project")

    values_to_remove = [
        "frameAgreementMidSized",
        "frameAgreementSmall",
        "frameAgreementGreenery",
        "frameAgreementSportSite",
        "directProcurement",
    ]

    qs = ConstructionProcurementMethod.objects.filter(value__in=values_to_remove)
    Project.objects.filter(constructionProcurementMethod__in=qs).update(constructionProcurementMethod=None)
    qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0096_alter_budgetoverrunreason_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_construction_procurement_method_value,
            reverse_update_construction_procurement_method_value,
        ),
    ]
