# Generated by Django 4.2.26 on 2026-04-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0097_auto_20260326_1011'),
        ('infraohjelmointi_api', '0097_project_phases_and_suspension'),
    ]

    operations = [
    ]
