# Generated by Django 4.2.26 on 2026-04-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0098_budgetoverrunreason_deleted_and_more'),
        ('infraohjelmointi_api', '0098_merge_20260415_1417'),
    ]

    operations = [
    ]
