# Generated by Django 4.2.26 on 2026-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0098_merge_20260415_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
