# Generated by Django 4.2.26 on 2026-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0099_merge_20260416_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staraprocurementreason',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='staraprocurementreason',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='staraprocurementreason',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
