# Generated by Django 4.2.26 on 2026-04-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0100_alter_person_phone_alter_person_title'),
        ('infraohjelmointi_api', '0100_alter_staraprocurementreason_options_and_more'),
    ]

    operations = [
    ]
