# Generated by Django 4.2.26 on 2026-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0101_merge_20260423_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
