# Generated by Django 4.2.26 on 2026-04-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0099_backfill_missing_project_type_and_qualifier'),
        ('infraohjelmointi_api', '0102_person_deleted'),
    ]

    operations = [
    ]
