# Generated by Django 4.2.26 on 2026-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0103_merge_20260430_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
