# Generated by Django 4.2.26 on 2026-05-06 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0104_update_person_phone_and_title_as_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConstructionHandover',
            fields=[
                ('history_user_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED_TO_PROGRAMMER', 'SUBMITTED_TO_PROGRAMMER'), ('SUBMITTED_TO_CONSTRUCTION', 'SUBMITTED_TO_CONSTRUCTION'), ('PROJECT_MANAGER_NAMED', 'PROJECT_MANAGER_NAMED'), ('MOVED_TO_CONSTRUCTION_PREPARATION', 'MOVED_TO_CONSTRUCTION_PREPARATION')], default='DRAFT', max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('constructionStart', models.DateField(blank=True, null=True)),
                ('constructionEnd', models.DateField(blank=True, null=True)),
                ('otherTimelineNotes', models.TextField(blank=True, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('linkDesignDrawings', models.URLField(blank=True, max_length=500, null=True)),
                ('linkCostAllocation', models.URLField(blank=True, max_length=500, null=True)),
                ('linkContractBoundaries', models.URLField(blank=True, max_length=500, null=True)),
                ('createdDate', models.DateTimeField(blank=True, editable=False)),
                ('updatedDate', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('constructionProcurementMethod', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.constructionprocurementmethod')),
                ('createdBy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('personFinancing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.projectprogrammer')),
                ('personPlanning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.person')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.project')),
                ('updatedBy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'verbose_name': 'historical construction handover',
                'verbose_name_plural': 'historical construction handovers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConstructionHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED_TO_PROGRAMMER', 'SUBMITTED_TO_PROGRAMMER'), ('SUBMITTED_TO_CONSTRUCTION', 'SUBMITTED_TO_CONSTRUCTION'), ('PROJECT_MANAGER_NAMED', 'PROJECT_MANAGER_NAMED'), ('MOVED_TO_CONSTRUCTION_PREPARATION', 'MOVED_TO_CONSTRUCTION_PREPARATION')], default='DRAFT', max_length=50)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('constructionStart', models.DateField(blank=True, null=True)),
                ('constructionEnd', models.DateField(blank=True, null=True)),
                ('otherTimelineNotes', models.TextField(blank=True, null=True)),
                ('totalCost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('linkDesignDrawings', models.URLField(blank=True, max_length=500, null=True)),
                ('linkCostAllocation', models.URLField(blank=True, max_length=500, null=True)),
                ('linkContractBoundaries', models.URLField(blank=True, max_length=500, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('constructionProcurementMethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.constructionprocurementmethod')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructionhandover_createdBy', to=settings.AUTH_USER_MODEL, to_field='uuid')),
                ('personFinancing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handovers_financing', to='infraohjelmointi_api.projectprogrammer')),
                ('personPlanning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handovers_planning', to='infraohjelmointi_api.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraohjelmointi_api.project')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='constructionhandover_updatedBy', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
