# Generated by Django 4.2.26 on 2026-05-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0105_historicalconstructionhandover_constructionhandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionhandover',
            name='constructionProjectManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handovers_pm', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='constructionhandover',
            name='previousProjectPhase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handovers_previous_phase', to='infraohjelmointi_api.projectphase'),
        ),
        migrations.AddField(
            model_name='historicalconstructionhandover',
            name='constructionProjectManager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.person'),
        ),
        migrations.AddField(
            model_name='historicalconstructionhandover',
            name='previousProjectPhase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.projectphase'),
        ),
    ]
