# Generated by Django 4.2.26 on 2026-05-12 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0106_constructionhandover_constructionprojectmanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionHandoverFinancing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financingParty', models.CharField(choices=[('KYMP', 'KYMP-rahoitus'), ('GLOBAL_CONNECT', 'GlobalConnect Oy'), ('HELEN', 'Helen Oy'), ('HELEN_SAHKO', 'Helen Sähköverkko Oy'), ('HSY', 'Helsingin seudun ympäristöpalvelut-kuntayhtymä HSY'), ('ELISA', 'Elisa Oyj'), ('DNA', 'DNA Oyj'), ('TELIA', 'Telia Finland Oyj'), ('AURIS', 'Auris Kaasunjakelu Oy'), ('CINIA', 'Cinia Cloud Oy'), ('KAUPUNKILIIKENNE', 'Pääkaupunkiseudun Kaupunkiliikenne Oy'), ('OTHER', 'Muu rahoitus')], max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('projectNumber', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('budgetItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_handover_financings', to='infraohjelmointi_api.budgetitem')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing', to='infraohjelmointi_api.constructionhandover')),
            ],
        ),
    ]
