# Generated by Django 4.2.26 on 2026-06-08

from django.db import migrations, models
import django.db.models.deletion


def clear_budgetitem_references(apps, schema_editor):
    ConstructionHandoverFinancing = apps.get_model(
        "infraohjelmointi_api", "ConstructionHandoverFinancing"
    )
    ConstructionHandoverFinancing.objects.exclude(budgetItem__isnull=True).update(
        budgetItem=None
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0107_constructionhandoverfinancing"),
    ]

    operations = [
        migrations.RunPython(clear_budgetitem_references, noop_reverse),
        migrations.AlterField(
            model_name="constructionhandoverfinancing",
            name="budgetItem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="construction_handover_financings",
                to="infraohjelmointi_api.projecttypequalifier",
            ),
        ),
    ]
