# Generated by Django 4.2.26 on 2026-06-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0108_alter_constructionhandoverfinancing_budgetitem'),
        ('infraohjelmointi_api', '0108_migrate_auditlog_to_resilient_logger'),
    ]

    operations = [
    ]
