# Generated by Django 4.2.26 on 2026-08-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0110_projectprogramme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionhandover',
            name='previousProjectPhaseDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handovers_previous_phase_detail', to='infraohjelmointi_api.projectphasedetail'),
        ),
        migrations.AddField(
            model_name='historicalconstructionhandover',
            name='previousProjectPhaseDetail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.projectphasedetail'),
        ),
    ]
