# Generated by Django 4.2.26 on 2026-08-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0111_phase_taxonomy'),
        ('infraohjelmointi_api', '0111_projectprogrammebasicinfo_estimatedcosts'),
    ]

    operations = [
    ]
