# Generated by Django 4.2.26 on 2026-08-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0111_constructionhandover_previousprojectphasedetail_and_more'),
        ('infraohjelmointi_api', '0111_phase_taxonomy'),
        ('infraohjelmointi_api', '0111_projectprogrammebasicinfo_estimatedcosts'),
    ]

    operations = [
    ]
