# Generated by Django 4.2.26 on 2026-08-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0112_merge_20260817_1451'),
        ('infraohjelmointi_api', '0112_merge_20260818_0905'),
    ]

    operations = [
    ]
