# Generated by Django 4.2.26 on 2026-08-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0112_noteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionHandoverAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='handover_attachments/%Y/%m/')),
                ('originalName', models.CharField(max_length=255)),
                ('contentType', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploadedDate', models.DateTimeField(auto_now_add=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='infraohjelmointi_api.constructionhandover')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_handover_attachments', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'ordering': ['uploadedDate'],
            },
        ),
    ]
