# Generated by Django 4.2.26 on 2026-08-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0113_remove_warranty_incomplete_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionhandover',
            name='staraProcurementReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infraohjelmointi_api.staraprocurementreason'),
        ),
        migrations.AddField(
            model_name='historicalconstructionhandover',
            name='staraProcurementReason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infraohjelmointi_api.staraprocurementreason'),
        ),
    ]
