# Generated by Django 4.2.26 on 2026-08-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0113_add_service_tunnel_classes'),
        ('infraohjelmointi_api', '0113_remove_warranty_incomplete_detail'),
    ]

    operations = [
    ]
