# Generated by Django 4.2.26 on 2026-08-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0114_constructionhandover_staraprocurementreason_and_more'),
        ('infraohjelmointi_api', '0114_merge_20260825_0939'),
    ]

    operations = [
    ]
