# Generated by Django 4.2.26 on 2026-09-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0116_alter_projectprogrammelink_contenttype_and_more'),
        ('infraohjelmointi_api', '0116_fix_service_tunnel_coordinator_parent'),
    ]

    operations = [
    ]
