# Generated by Django 4.2.26 on 2026-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0117_merge_20260903_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectprogrammetrafficplanningcriteria',
            name='carTraffic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalprojectprogrammetrafficplanningcriteria',
            name='targetTrafficChanges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectprogrammetrafficplanningcriteria',
            name='carTraffic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectprogrammetrafficplanningcriteria',
            name='targetTrafficChanges',
            field=models.TextField(blank=True),
        ),
    ]
