# Generated by Django 4.2.26 on 2026-10-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('infraohjelmointi_api', '0121_constructionhandoverattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgrammeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sectionId', models.UUIDField()),
                ('file', models.FileField(upload_to='project_programme_attachments/%Y/%m/')),
                ('originalName', models.CharField(max_length=255)),
                ('contentType', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploadedDate', models.DateTimeField(auto_now_add=True)),
                ('sectionType', models.ForeignKey(help_text='References to any type of a section (basic info, design criteria, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_project_programme_attachments', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'ordering': ['uploadedDate'],
                'indexes': [models.Index(fields=['sectionType', 'sectionId'], name='infraohjelm_section_c02e27_idx')],
            },
        ),
    ]
