# Generated by Django 4.2.26 on 2026-10-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infraohjelmointi_api', '0122_projectprogrammeattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgrammeLocationMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='project_programme_location_maps/%Y/%m/')),
                ('originalName', models.CharField(max_length=255)),
                ('contentType', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploadedDate', models.DateTimeField(auto_now_add=True)),
                ('project_programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locationMap', to='infraohjelmointi_api.projectprogramme')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_project_programme_location_maps', to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
        ),
    ]
