# Generated by Django 4.1.3 on 2022-12-22 15:10

from django.db import migrations


def populate_ProjectClasses_data(apps, schema_editor):
    ProjectClass = apps.get_model("infraohjelmointi_api", "ProjectClass")
    # Capitalize classnames
    projectClasses = [
        {"name": "8 01 KIINTEA OMAISUUS", "parent": None},
        {
            "name": "8 01 03 ESIRAKENTAMINEN, TÄYTTÖTYÖT, RAK. KELP.SAATTAM.",
            "parent": "8 01 KIINTEA OMAISUUS",
        },
        {
            "name": "8 01 03 01 MUU ESIRAKENTAMINEN",
            "parent": "8 01 03 ESIRAKENTAMINEN, TÄYTTÖTYÖT, RAK. KELP.SAATTAM.",
        },
        {
            "name": "8 01 03 02 Täydennysrakentamiskorvaukset",
            "parent": "8 01 03 ESIRAKENTAMINEN, TÄYTTÖTYÖT, RAK. KELP.SAATTAM.",
        },
        {
            "name": "8 03 KADUT JA LIIKENNEVAYLAT",
            "parent": None,
        },
        {
            "name": "8 03 01 01 UUDISRAKENTAMINEN",
            "parent": "8 03 KADUT JA LIIKENNEVAYLAT",
        },
        {
            "name": "Eteläinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Läntinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Keskinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Pohjoinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Koillinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Kaakkoinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Itäinen suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Östersundomin suurpiiri",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "Meluesteet",
            "parent": "8 03 01 01 UUDISRAKENTAMINEN",
        },
        {
            "name": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
            "parent": "8 03 KADUT JA LIIKENNEVAYLAT",
        },
        {
            "name": "Katujen peruskorjaukset",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "Siltojen peruskorjaus ja uusiminen",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "Päällysteiden uusiminen",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "Joukkoliikenteen kehittäminen",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "Liikennejärjestelyt",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "Jalankulun ja pyöräilyn väylät",
            "parent": "8 03 01 02 PERUSPARANTAMINEN JA LIIKENNEJÄRJESTELYT",
        },
        {
            "name": "8 03  01 03 MUUT INVESTOINNIT",
            "parent": "8 03 KADUT JA LIIKENNEVAYLAT",
        },
        {
            "name": "Täytemaan vastaanottopaikat",
            "parent": "8 03  01 03 MUUT INVESTOINNIT",
        },
        {
            "name": "Lumenvastaanottopaikat ja hiekkasiilot",
            "parent": "8 03  01 03 MUUT INVESTOINNIT",
        },
        {
            "name": "Yleiset käymälät",
            "parent": "8 03  01 03 MUUT INVESTOINNIT",
        },
        {
            "name": "Ranta-alueiden kunnostus (tulvasuojarak.)",
            "parent": "8 03  01 03 MUUT INVESTOINNIT",
        },
        {
            "name": "8 03 03 YHTEISHANKKEET VÄYLÄVIRASTO",
            "parent": "8 03 KADUT JA LIIKENNEVAYLAT",
        },
        {
            "name": "8 04 PUISTOT JA LIIKUNTA-ALUEET",
            "parent": None,
        },
        {
            "name": "UUDET PUISTOT",
            "parent": "8 04 PUISTOT JA LIIKUNTA-ALUEET",
        },
        {
            "name": "PUISTOJEN PERUSKORJAUS",
            "parent": "8 04 PUISTOT JA LIIKUNTA-ALUEET",
        },
        {
            "name": "Uudet liikuntapaikat ja ulkoilualueet",
            "parent": "8 04 PUISTOT JA LIIKUNTA-ALUEET",
        },
        {
            "name": "Liikunta- ja ulkoilualueiden peruskorjaus",
            "parent": "8 04 PUISTOT JA LIIKUNTA-ALUEET",
        },
        {
            "name": "8 08 PROJEKTIALUEIDEN INFRARAKENTAMINEN, Khn käytettäväksi",
            "parent": None,
        },
        {
            "name": "8 08 01 ESIRAKENTAMINEN",
            "parent": "8 08 PROJEKTIALUEIDEN INFRARAKENTAMINEN, Khn käytettäväksi",
        },
    ]
    for _class in projectClasses:
        if _class["parent"] != None:
            parent, _ = ProjectClass.objects.get_or_create(name=_class["parent"])
            parent.parentClass.create(name=_class["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("infraohjelmointi_api", "0019_projectclass"),
    ]

    operations = [migrations.RunPython(populate_ProjectClasses_data)]
