name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.11
      postgres-major-version: 17
      extra-commands: |
        echo "APP_NAME=infraohjelmointi" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
        
        coverage run --source='.' manage.py test
        coverage report
        coverage xml

