name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.11
      postgres-major-version: 17
      extra-commands: |
        echo "DJANGO_SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
        cp .env.template .env
        sed -i '/DATABASE_URL/d' .env

        sudo locale-gen fi_FI.UTF-8
        mkdir static
        
        coverage run --source='.' manage.py test
        coverage report
        coverage xml

